S02US05-connexion
WildCodeSchool/orleans-202109-php-project-cerha pull request #136
Opened 2021-12-20 18:22 UTC by Halphane

2021-12-20 20:10 UTC, WeisgerberEstelle approved these changes

2021-12-21 08:20 UTC, sblondeau requested changes

2021-12-21 08:20 UTC, sblondeau commented on src/Controller/SecurityController.php
> +     * @Route("/login", name="login")
tu peux mettre les routes en français (connexion, deconnexion)

2021-12-21 08:20 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +            $user->setRoles(['ROLE_USER']);
pas besoin de setter le ROLE_USER, il y est par défaut

2021-12-21 08:20 UTC, sblondeau commented on templates/items/_navbar.html.twig
> +				{% if app.user %}
utilise plutot `{% if is_granted('IS_AUTHENTICATED_FULLY') %}`
qui permet de tester si un user est authentifié correctement

2021-12-21 08:20 UTC, sblondeau commented on templates/items/_navbar.html.twig
>  		<div class="navbar-nav order-lg-last order-xs-2 ms-auto me-2">
si l'user est connecté, ce lien ne devrait plus apparaître (car il renvoie vers la page login)

2021-12-21 11:08 UTC, sblondeau approved these changes

2021-12-21 11:08 UTC, merged