fixed logos colors and put legal notice at the bottom
WildCodeSchool/orleans-202109-php-project-cerha pull request #141
Opened 2021-12-21 19:32 UTC by ThibaultFoure

2021-12-21 19:41 UTC, WeisgerberEstelle submitted a review, later dismissed

2021-12-21 22:53 UTC, sblondeau requested changes

2021-12-21 22:53 UTC, sblondeau commented on migrations/Version20211221154012.php
> +<?php
tu n'as pas besoin de migration dans ton fix, attention à ne pas envoyer des fichiers de migrations non nécessaires, car ils ont tous un nom différent, donc git considère 2 fichiers distinct et donc pas de conflit. Et les migrations vont planter.
Ne jamais faire de make:migration si on ne mets pas à jour la bdd dans son US ;-) suelement des doctrine:migration:migration pour mettre à jour sa base

2021-12-22 09:46 UTC, sblondeau approved these changes

2021-12-22 09:46 UTC, merged