Edit-Candidat
WildCodeSchool/orleans-202109-php-project-cerha pull request #144
Opened 2021-12-22 21:38 UTC by Bsir-Rachida

2021-12-22 21:44 UTC, Halphane approved these changes

2021-12-29 13:56 UTC, sblondeau requested changes

2021-12-29 13:56 UTC, sblondeau commented on src/Entity/Candidat.php
> +     * @Assert\NotBlank
pas integer mas string 
et ajouter un assert length

2021-12-29 13:56 UTC, sblondeau commented on src/Controller/CandidatController.php
> +        return $this->renderForm('candidat/form/edit.contactDetails.html.twig', [
ton nom de fichier est bizarre, ça devrait plutot etre qq chose comme candidate/editContact.html.twig

2021-12-29 13:56 UTC, sblondeau commented on src/Form/ContactDetailsType.php
> +            ->add('address', TextType::class, ['label' => 'Addresse'])
adresse (un seul D en français) pour le label

2021-12-29 13:56 UTC, sblondeau commented on templates/candidat/form/edit.contactDetails.html.twig
> +					{% for message in app.flashes('success') %}
non il faut afficher les messages flash de manière globale dans le fichier base (voir la doc ou la quete sur les messages flash)

2021-12-30 14:09 UTC, Bsir-Rachida commented on templates/candidat/form/edit.contactDetails.html.twig
> +					{% for message in app.flashes('success') %}
En faite on modifie chaque bloc séparément  et du coup j ai que cette page

2021-12-30 14:32 UTC, ThibaultFoure requested changes
un tout petit e en trop mais c'est ok

2021-12-30 14:32 UTC, ThibaultFoure commented on src/Form/ContactDetailsType.php
> +            ->add('postalCode', TextType::class, ['label' => 'Code postale'])
code postal sans e

2021-12-30 14:55 UTC, ThibaultFoure approved these changes

2022-01-02 16:39 UTC, sblondeau commented on templates/candidat/form/edit.contactDetails.html.twig
> +					{% for message in app.flashes('success') %}
oui mais au final tu en auras besoin un peu partout sur le site donc vaut mieux en mettre un de manière générale dans le base ! et pas limiter à success... au pire enlève cette partie et vous ferez un fix pour gérer les messages flash

2022-01-02 16:40 UTC, sblondeau commented on src/Entity/Candidat.php
> +     * @Assert\NotBlank
manque tjs le assert length

2022-01-02 16:41 UTC, sblondeau requested changes

2022-01-02 16:41 UTC, sblondeau commented on templates/candidat/edit/edit.contactDetails.html.twig
> +					{% for message in app.flashes('success') %}
il faut le mettre dans base. Et ne pas limiter à success ici.
au pire retire cette partie et vous ferez un fix général pour les messages flash

2022-01-03 11:57 UTC, closed without merging