S02 us09 company infos
WildCodeSchool/orleans-202109-php-project-cerha pull request #149
Opened 2021-12-30 11:33 UTC by ThibaultFoure

2021-12-30 14:44 UTC, Bsir-Rachida submitted a review, later dismissed

2022-01-03 07:59 UTC, sblondeau requested changes

2022-01-03 07:59 UTC, sblondeau commented on src/DataFixtures/CompanyFixtures.php
> +            $company->setVatNumber('FR' . rand(10000000001, 99999999999));
https://fakerphp.github.io/locales/fr_FR/#fakerproviderfr_frpayment
tu as un vat dans faker

2022-01-03 07:59 UTC, sblondeau commented on src/DataFixtures/CompanyFixtures.php
> +            $company->setPostalCode(preg_replace('/\s+/', '', $faker->postcode));
bizarre ça ? tu as des espaces à retirer ?

2022-01-03 08:10 UTC, ThibaultFoure commented on src/DataFixtures/CompanyFixtures.php
> +            $company->setPostalCode(preg_replace('/\s+/', '', $faker->postcode));
J'ai l'impression que le code postal généré est de type '45 100' parce que j'ai créé un CHAR(5) en bdd et ça ne passe pas

2022-01-03 14:37 UTC, WeisgerberEstelle approved these changes

2022-01-03 15:42 UTC, sblondeau approved these changes

2022-01-03 15:42 UTC, merged