US14-S02-Candidat-Formation
WildCodeSchool/orleans-202109-php-project-cerha pull request #162
Opened 2022-01-04 08:36 UTC by Bsir-Rachida

2022-01-04 11:13 UTC, WeisgerberEstelle requested changes

2022-01-04 11:13 UTC, WeisgerberEstelle commented on src/DataFixtures/FormationFixtures.php
> +}
tes methodes ne sont pas en camelcase, ca marche quand meme?

2022-01-04 12:49 UTC, Halphane submitted a review, later dismissed

2022-01-05 10:15 UTC, Halphane approved these changes

2022-01-05 10:18 UTC, sblondeau approved these changes

2022-01-05 10:18 UTC, merged