Us15 1 s02 candidat experiences
WildCodeSchool/orleans-202109-php-project-cerha pull request #163
Opened 2022-01-04 11:20 UTC by Bsir-Rachida

2022-01-04 12:45 UTC, Halphane submitted a review, later dismissed

2022-01-04 16:51 UTC, sblondeau requested changes

2022-01-04 16:51 UTC, sblondeau commented on src/DataFixtures/ExperienceFixtures.php
> +            $experience->setCandidat($this->getReference('candidat_john'));
ça serait quand meme bien mieux d'avoir des fixtures qui ne soient pas relié uniquement à candiat_john, sinon dès que tu vas attaquer la partie admin, tu n'auras aucune infos sur les autres candidats et tu seras coincée.

2022-01-05 09:23 UTC, ThibaultFoure submitted a review, later dismissed

2022-01-05 09:27 UTC, Halphane requested changes

2022-01-05 09:27 UTC, Halphane commented on src/DataFixtures/UserFixtures.php
> +            $user->setPassword($this->passwordHasher->hashPassword($user, 'test'));
Pourquoi tu modifie le mdp des user ?

2022-01-05 09:36 UTC, Halphane requested changes

2022-01-05 09:36 UTC, Halphane commented on src/DataFixtures/CandidatFixtures.php
Du coup tu n'as plus de fixtures pour tes candidat,  Boucle et utilise faker pour en créer une dizaine (y'a pas les addresse française mais par contre les addresse américaine fonctionne donc check la doc)

2022-01-05 09:36 UTC, Bsir-Rachida commented on src/DataFixtures/UserFixtures.php
> +            $user->setPassword($this->passwordHasher->hashPassword($user, 'test'));
pour qu on puissent tester les  différents profils

2022-01-05 09:44 UTC, Halphane commented on src/DataFixtures/UserFixtures.php
> +            $user->setPassword($this->passwordHasher->hashPassword($user, 'test'));
tu créer un profil avec un mdp que tu connais comme j'ai fais pour john.
On est pas censé avoir accès au compte des autre.
En plus pour se connecter ce sera un galère vu que y'aura des email complexe a aller chercher a chaque fois vu que c'est aléatoire.

2022-01-05 09:44 UTC, Halphane commented on src/DataFixtures/UserFixtures.php
> +            $user->setPassword($this->passwordHasher->hashPassword($user, 'test'));
Genre tu créer un user Fabrice avec une email genre fabrice@gmail.com et le mdp c'est candidat.

2022-01-05 09:56 UTC, Halphane approved these changes

2022-01-05 10:33 UTC, sblondeau approved these changes

2022-01-05 13:56 UTC, WeisgerberEstelle approved these changes

2022-01-05 13:58 UTC, merged