S02 us17 display languages candidat
WildCodeSchool/orleans-202109-php-project-cerha pull request #164
Opened 2022-01-04 16:02 UTC by WeisgerberEstelle

2022-01-04 21:15 UTC, ThibaultFoure commented on src/DataFixtures/CandidatLanguageFixtures.php
> +use App\Entity\CandidatLanguage;
Pareil, tout s'appelle "Candidat" alors que tous les autres noms sont en anglais

2022-01-04 21:33 UTC, ThibaultFoure submitted a review, later dismissed

2022-01-05 08:36 UTC, Halphane approved these changes

2022-01-05 08:43 UTC, sblondeau requested changes
et globalement y a effectivement un pb de nommage à plein d'endroit, c'est candidat**e** avec un E à la fin.
Si c'est plus simple, tu peux faire un fix juste après, ou corriger maintenant

2022-01-05 08:43 UTC, sblondeau commented on src/Controller/CandidatController.php
> +use App\Entity\Candidat;
+1

2022-01-05 08:43 UTC, sblondeau commented on src/DataFixtures/CandidatLanguageFixtures.php
> +        foreach (self::LANGUAGES as $language) {
ne limite pas tes fixture à john, les autres users doivent aussi avoir des languages, tu peux faire 2 boucles imbriquées, et enventuellement un peu de random pour pas avoir la meme chose pour tout le monde

2022-01-11 09:43 UTC, Halphane submitted a review, later dismissed

2022-01-11 09:50 UTC, sblondeau submitted a review, later dismissed

2022-01-11 10:23 UTC, Halphane approved these changes

2022-01-11 10:46 UTC, merged