S02US07-Incription
WildCodeSchool/orleans-202109-php-project-cerha pull request #169
Opened 2022-01-05 14:32 UTC by Halphane

2022-01-05 15:41 UTC, Bsir-Rachida approved these changes

2022-01-05 16:30 UTC, sblondeau requested changes

2022-01-05 16:30 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +                    ->from(new Address('nathan-chapelle_student2021@wilder.school', 'CERHA Confirmation'))
faut pas que tu mettes ton adresse en dur, faut que ça passe par un paramètre dans service.yaml, lui meme venant d'une variable d'environnement (MAILER_ADMIN par ex) dans env.local (à mettre dans .env aussi en modèle)

2022-01-05 16:30 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +        $this->addFlash('success', 'Votre addresse email a été vérifié.');
vérifiée

2022-01-05 16:30 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Length(max = 255)
attention ton max length est de 255 alors que la bdd est config avec 180 !

2022-01-06 17:15 UTC, Bsir-Rachida approved these changes

2022-01-06 22:55 UTC, sblondeau approved these changes

2022-01-06 22:55 UTC, merged