US12-S02-Edit-User-candidat
WildCodeSchool/orleans-202109-php-project-cerha pull request #171
Opened 2022-01-06 09:34 UTC by Bsir-Rachida

2022-01-06 10:16 UTC, ThibaultFoure approved these changes

2022-01-06 10:24 UTC, sblondeau requested changes

2022-01-06 10:24 UTC, sblondeau commented on src/Entity/User.php
> +       * @Assert\Email()
manque assert length de 180

2022-01-06 10:24 UTC, sblondeau commented on src/Entity/User.php
>  /**
manque un assert unique sur l'email ici

2022-01-06 10:24 UTC, sblondeau commented on src/Entity/User.php
>       * @ORM\Column(type="integer")
pas de integer pour un phone number car 06 devient 6 sinon et tous les autres caractères ne fonctionneraient pas (espace, tiret, le + de +33...)

2022-01-06 10:24 UTC, sblondeau commented on src/Form/ContactDetailsType.php
> +            ->add('user', UserCandidateType::class, ['label' => ' '])
je crois que c'est label=>false ou label=>null ou label=> '', à verif sur la doc, mais sans doute pas label => '*espace*'

2022-01-06 21:32 UTC, ThibaultFoure commented on src/Entity/User.php
>  /**
je crois qu'il manque toujours le assert réclamé par M. Blondeau

2022-01-07 13:14 UTC, Bsir-Rachida commented on src/Entity/User.php
>  /**
non finalement on va pas editer l email

2022-01-07 14:46 UTC, ThibaultFoure approved these changes
Super Rachida bien joué !

2022-01-07 15:07 UTC, sblondeau approved these changes

2022-01-07 15:07 UTC, merged