S03 us38 read candidate
WildCodeSchool/orleans-202109-php-project-cerha pull request #187
Opened 2022-01-10 11:38 UTC by Halphane

2022-01-10 11:47 UTC, Bsir-Rachida submitted a review, later dismissed

2022-01-10 13:17 UTC, sblondeau requested changes

2022-01-10 13:17 UTC, sblondeau commented on src/Controller/AdminCandidateController.php
> +            'candidats' => $candidatRepository->findAll(),
trier par ordre alpha ?

2022-01-10 13:17 UTC, sblondeau commented on templates/admin_candidate/index.html.twig
> +                <td class="align-middle">{{ candidat.city ?? 'aucune donnée' }}</td>
je laisserais vide plutot que "aucune donnée", comme ça on voit tout de suite que c'est vide

2022-01-10 13:17 UTC, sblondeau commented on templates/admin_candidate/index.html.twig
> +                <td colspan="9">Aucun candidats trouvé</td>
aucun candidat trouvé

2022-01-11 09:41 UTC, WeisgerberEstelle approved these changes

2022-01-11 09:51 UTC, sblondeau approved these changes

2022-01-11 09:51 UTC, merged