S02 us28 edit company details
WildCodeSchool/orleans-202109-php-project-cerha pull request #188
Opened 2022-01-10 16:14 UTC by ThibaultFoure

2022-01-10 18:03 UTC, Bsir-Rachida approved these changes

2022-01-11 08:02 UTC, sblondeau requested changes

2022-01-11 08:02 UTC, sblondeau commented on src/Entity/Company.php
> +     * @Assert\NotBlank
les num de siret se valident avec un algo de Luhn, voir wikipedia
Ce validateur existe dans symfony, à ajouter ;-)

2022-01-11 08:02 UTC, sblondeau commented on src/Entity/Company.php
>      private string $vatNumber;
il doit en théorie pouvoir se calculer depuis le siret + pays 
ça serait super intéressant de créer un validateur custom + des tests :D mais on va dire que c'est sans doute pas la prio ^^

2022-01-11 09:46 UTC, Halphane approved these changes

2022-01-11 09:51 UTC, sblondeau approved these changes

2022-01-11 09:51 UTC, merged