S03 us27 create form for complementary questions
WildCodeSchool/orleans-202109-php-project-cerha pull request #203
Opened 2022-01-11 20:54 UTC by WeisgerberEstelle

2022-01-12 12:44 UTC, ThibaultFoure approved these changes

2022-01-12 13:57 UTC, sblondeau requested changes

2022-01-12 13:57 UTC, sblondeau commented on src/Form/ComplementaryQuestionType.php
> +                'label' => 'Vous qualifierez votre recherche : d\'efficace,
question : est-ce pertinent d'avoir la question en label ? 
je trouverais ça plus logique d'avoir une question (en h3 par ex)
puis un label : réponse ?

2022-01-12 18:16 UTC, ThibaultFoure approved these changes

2022-01-13 10:20 UTC, sblondeau approved these changes

2022-01-13 13:06 UTC, sblondeau approved these changes

2022-01-13 13:06 UTC, merged