fix-style-card
WildCodeSchool/orleans-202109-php-project-cerha pull request #218
Opened 2022-01-12 13:36 UTC by Bsir-Rachida

2022-01-12 15:22 UTC, WeisgerberEstelle requested changes

2022-01-12 15:22 UTC, WeisgerberEstelle commented on assets/styles/profile.scss
> +}
mauvaise indentadion

2022-01-12 18:19 UTC, ThibaultFoure approved these changes

2022-01-13 10:26 UTC, sblondeau approved these changes

2022-01-13 10:26 UTC, merged