S03 us07 bis intermediate form
WildCodeSchool/orleans-202109-php-project-cerha pull request #230
Opened 2022-01-13 20:07 UTC by WeisgerberEstelle

2022-01-13 21:40 UTC, ThibaultFoure submitted a review, later dismissed

2022-01-14 08:14 UTC, sblondeau requested changes

2022-01-14 08:14 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +            $_POST['user'] = $user;
oh ?! bah non pas de $_POST !

2022-01-14 08:14 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +                return $this->redirectToRoute('register_candidat', ['id' => $userId]);
tu rediriges les 2 fois vers register_candidat

2022-01-14 08:14 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +            if ($form->get('type')->getData() == 'Entreprise') {
fait une constante USER_TYPE dans ton entity User avec 2 entrée entreprises et candidat ?  tu peux te servir de cette constante pour ton ChoiceType et la réutiliser ici, ça sera plus propre

C'est sans doute une autre US, mais il faudra aussi penser à setter le ROLE au user en fonction de Entreprise ou candidat

2022-01-14 08:14 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +        $user = $userRepository->findOneById($_GET['id']);
pas de $_GET.
en fait je pense que je ne comprends pas trop ce que tu cherches à faire ici :/ on en reparle

2022-01-17 09:25 UTC, Halphane approved these changes

2022-01-17 11:13 UTC, sblondeau requested changes

2022-01-17 11:13 UTC, sblondeau commented on src/Form/RegistrationFormType.php
> +                    'Une entreprise' => 'company',
fais une autre constante que tu appelles par ex USER_ROLES = ['candidate'=> 'Candidat', 'company'=>'Entreprise'] dans ton entité User.
Tu réutilises cette constante dans ton choiceType 'choices'=>User::USER_ROLES

2022-01-17 11:13 UTC, sblondeau commented on src/Controller/RegistrationController.php
> +            if ($form->get('type')->getData() == 'candidate') {
créé 2 constantes USER_CANDIDATE = 'candidate' et USER_COMPANY = 'company'
et utilise ces constantes ici pour éviter les valeurs 'en dur' dans tes conditions

et il faudrait aussi que tu set les roles des user (ROLE_COMPANY et ROLE_CANDIDATE ici non ? )

2022-01-17 17:17 UTC, Bsir-Rachida submitted a review, later dismissed

2022-01-18 07:57 UTC, sblondeau commented
je ne vois pas les modifs :o

2022-01-18 09:14 UTC, Bsir-Rachida approved these changes

2022-01-18 11:03 UTC, sblondeau approved these changes

2022-01-18 11:03 UTC, merged