Us31 s01 page contact
WildCodeSchool/orleans-202109-php-project-cerha pull request #28
Opened 2021-12-14 16:32 UTC by Bsir-Rachida

2021-12-14 19:02 UTC, ThibaultFoure approved these changes

2021-12-15 08:50 UTC, sblondeau requested changes

2021-12-15 08:50 UTC, sblondeau commented on templates/contact/index.html.twig
> +							<div class="vr"></div>
c'est quoi cette div (avec en plus du style inline ?

2021-12-15 08:50 UTC, sblondeau commented on src/Controller/ContactController.php
> +            'controller_name' => 'ContactController',
enlever le param controller_name qui est juste mis pour l'exemple quand tu fais le make:controller

2021-12-15 08:58 UTC, Bsir-Rachida commented on templates/contact/index.html.twig
> +							<div class="vr"></div>
le vr c'est un séparateur

2021-12-15 09:07 UTC, ThibaultFoure approved these changes

2021-12-15 09:22 UTC, sblondeau approved these changes

2021-12-15 09:22 UTC, merged