create view and route for profile public
WildCodeSchool/orleans-202109-php-project-cerha pull request #322
Opened 2022-01-24 15:51 UTC by WeisgerberEstelle

2022-01-24 16:36 UTC, sblondeau requested changes

2022-01-24 16:36 UTC, sblondeau commented on templates/candidate/components/_complementary-questions.html.twig
> +		{% if not is_granted("ROLE_ADMIN") and not is_granted("ROLE_COMPANY") %}
ça marche pas si tu met plutot 
		{% if not is_granted("ROLE_ADMIN") and is_granted("ROLE_CANDIDATE") %}
ça doit revenir au meme mais c'est plus logique non ?

2022-01-24 16:36 UTC, sblondeau commented on templates/candidate/components/_complementary-questions.html.twig
> +		{% if not is_granted("ROLE_ADMIN") and not is_granted("ROLE_COMPANY") %}
idem en dessous

2022-01-25 08:51 UTC, Bsir-Rachida approved these changes

2022-01-25 09:03 UTC, sblondeau approved these changes

2022-01-25 09:03 UTC, merged