employee form fixed
WildCodeSchool/orleans-202109-php-project-cerha pull request #373
Opened 2022-01-27 15:05 UTC by WeisgerberEstelle

2022-01-27 15:10 UTC, Bsir-Rachida submitted a review, later dismissed

2022-01-27 16:55 UTC, sblondeau requested changes

2022-01-27 16:55 UTC, sblondeau commented on src/Entity/Employee.php
> +     * @Assert\NotBlank
hum pourquoi un NotBlank sur une propriété qui accepte un objet File ?

2022-01-28 08:35 UTC, Bsir-Rachida approved these changes

2022-01-28 08:37 UTC, sblondeau approved these changes

2022-01-28 08:37 UTC, merged