S01US02_Footer
WildCodeSchool/orleans-202109-php-project-cerha pull request #40
Opened 2021-12-16 14:01 UTC by ThibaultFoure

2021-12-16 14:03 UTC, WeisgerberEstelle approved these changes

2021-12-17 09:47 UTC, sblondeau requested changes
image qr beaucoup trop lourde.
100ko max

2021-12-17 09:48 UTC, sblondeau requested changes

2021-12-17 09:48 UTC, sblondeau commented on templates/items/_footer.html.twig
> +		<div class="col-lg-4 col-xs-12 mt-3 d-flex justify-content-center legalNotice">
pas col-xs-12, ça n'existe pas, ça serait col-12. Mais pour le coup c'est déjà la valeur par defaut donc tu peux l'enlever completement

2021-12-17 10:06 UTC, Bsir-Rachida submitted a review, later dismissed

2021-12-17 10:13 UTC, sblondeau approved these changes

2021-12-17 10:14 UTC, merged