S01 us04 display services cards homepage
WildCodeSchool/orleans-202109-php-project-cerha pull request #41
Opened 2021-12-16 15:01 UTC by WeisgerberEstelle

2021-12-16 16:03 UTC, ThibaultFoure requested changes

2021-12-16 16:03 UTC, ThibaultFoure commented on assets/styles/home.scss
> +
ligne vide

2021-12-16 16:03 UTC, ThibaultFoure commented on templates/home/index.html.twig
> -
Pourquoi tu supprimes le title ?

2021-12-16 16:14 UTC, ThibaultFoure approved these changes

2021-12-17 09:49 UTC, sblondeau requested changes

2021-12-17 09:49 UTC, sblondeau commented on templates/home/index.html.twig
> +{% block title %} {{ parent() }} Home{% endblock %}
en français par contre le title

2021-12-17 10:11 UTC, Halphane approved these changes

2021-12-17 10:16 UTC, sblondeau approved these changes

2021-12-17 10:16 UTC, merged