added images and text
WildCodeSchool/orleans-202109-php-project-cerha pull request #482
Opened 2022-02-07 15:11 UTC by Halphane

2022-02-07 15:25 UTC, ThibaultFoure requested changes

2022-02-07 15:25 UTC, ThibaultFoure commented on src/DataFixtures/EmployeeFixtures.php
> +            'civility' => 'M',
le pooiiiiiiiiinnnnnnntttttttt après M

2022-02-07 15:37 UTC, Halphane commented on src/DataFixtures/EmployeeFixtures.php
> +            'civility' => 'M',
le point s'affiche en dur

2022-02-07 15:45 UTC, ThibaultFoure requested changes

2022-02-07 15:48 UTC, ThibaultFoure submitted a review, later dismissed

2022-02-08 15:42 UTC, ThibaultFoure submitted a review, later dismissed

2022-02-08 15:57 UTC, sblondeau requested changes
tu as encore une image à 18M

2022-02-09 10:13 UTC, sblondeau approved these changes

2022-02-09 10:13 UTC, merged